version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
    - 9090:9090
    hostname: prometheus
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./PrometheusData:/prometheus"
