version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
    - 9090:9090
    hostname: prometheus
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./PrometheusData:/prometheus"
  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    ports:
    - 9115:9115
    depends_on:
    - prometheus
    hostname: blackbox
