version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
    - 9090:9090
    restart: always
    hostname: prometheus
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./PrometheusData:/prometheus"
  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    ports:
    - 9115:9115
    depends_on:
    - prometheus
    restart: always
    hostname: blackbox
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes: 
      - "./provisioning:/etc/grafana/provisioning"
    restart: always
    depends_on:
    - prometheus